# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BarcodeScanner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BarcodeScanner
pod 'Kingfisher', '~> 5.0'
pod 'SwiftyJSON', '~> 4.0'
pod 'Alamofire', '~> 5.2'

  target 'BarcodeScannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BarcodeScannerUITests' do
    # Pods for testing
  end

end
